<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Customer;

class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $customers = [
            [   
                'id' => 103, 
                'customer_name' => 'Atelier graphique', 
                'contact_last_name' => 'Schmitt', 
                'contact_first_name' => 'Carine ', 
                'phone' => '40.32.2555', 
                'address_line_1' => '54, rue Royale',
                'address_line_2' => NULL,
                'city' => 'Nantes', 
                'state' => NULL, 
                'postal_code' => '44000', 
                'country' => 'France', 
                'sales_rep_employee_id' =>  1370, 
                'credit_limit' => '21000.00'
            ],
            [   
                'id' => 112, 
                'customer_name' => 'Signal Gift Stores', 
                'contact_last_name' => 'King', 
                'contact_first_name' => 'Jean', 
                'phone' => '7025551838', 
                'address_line_1' => '8489 Strong St.',
                'address_line_2' => NULL,
                'city' => 'Las Vegas', 
                'state' => 'NV', 
                'postal_code' => '83030', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1166, 
                'credit_limit' => '71800.00'
            ],
            [   
                'id' => 114, 
                'customer_name' => 'Australian Collectors, Co.', 
                'contact_last_name' => 'Ferguson', 
                'contact_first_name' => 'Peter', 
                'phone' => '03 9520 4555', 
                'address_line_1' => '636 St Kilda Road',
                'address_line_2' => 'Level 3',
                'city' => 'Melbourne', 
                'state' => 'Victoria', 
                'postal_code' => '3004', 
                'country' => 'Australia', 
                'sales_rep_employee_id' =>  1611, 
                'credit_limit' => '117300.00'
            ],
            [   
                'id' => 119, 
                'customer_name' => 'La Rochelle Gifts', 
                'contact_last_name' => 'Labrune', 
                'contact_first_name' => 'Janine ', 
                'phone' => '40.67.8555', 
                'address_line_1' => '67, rue des Cinquante Otages',
                'address_line_2' => NULL,
                'city' => 'Nantes', 
                'state' => NULL, 
                'postal_code' => '44000', 
                'country' => 'France', 
                'sales_rep_employee_id' =>  1370, 
                'credit_limit' => '118200.00'
            ],
            [   
                'id' => 121, 
                'customer_name' => 'Baane Mini Imports', 
                'contact_last_name' => 'Bergulfsen', 
                'contact_first_name' => 'Jonas ', 
                'phone' => '07-98 9555', 
                'address_line_1' => 'Erling Skakkes gate 78',
                'address_line_2' => NULL,
                'city' => 'Stavern', 
                'state' => NULL, 
                'postal_code' => '4110', 
                'country' => 'Norway', 
                'sales_rep_employee_id' =>  1504, 
                'credit_limit' => '81700.00'
            ],
            [   
                'id' => 124, 
                'customer_name' => 'Mini Gifts Distributors Ltd.', 
                'contact_last_name' => 'Nelson', 
                'contact_first_name' => 'Susan', 
                'phone' => '4155551450', 
                'address_line_1' => '5677 Strong St.',
                'address_line_2' => NULL,
                'city' => 'San Rafael', 
                'state' => 'CA', 
                'postal_code' => '97562', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1165, 
                'credit_limit' => '210500.00'
            ],
            [   
                'id' => 125, 
                'customer_name' => 'Havel & Zbyszek Co', 
                'contact_last_name' => 'Piestrzeniewicz', 
                'contact_first_name' => 'Zbyszek',
                'phone' => '(26) 642-7555',
                'address_line_1' => 'ul. Filtrowa 68',
                'address_line_2' => NULL,
                'city' => 'Warszawa', 
                'state' => NULL, 
                'postal_code' => '01-012', 
                'country' => 'Poland', 
                'sales_rep_employee_id' =>  NULL, 
                'credit_limit' => '0.00'
            ],
            [   
                'id' => 128, 
                'customer_name' => 'Blauer See Auto, Co.', 
                'contact_last_name' => 'Keitel', 
                'contact_first_name' => 'Roland', 
                'phone' => '+49 69 66 90 2555',
                'address_line_1' => 'Lyonerstr. 34',
                'address_line_2' => NULL,
                'city' => 'Frankfurt', 
                'state' => NULL, 
                'postal_code' => '60528', 
                'country' => 'Germany', 
                'sales_rep_employee_id' =>  1504, 
                'credit_limit' => '59700.00'
            ],
            [   
                'id' => 129, 
                'customer_name' => 'Mini Wheels Co.', 
                'contact_last_name' => 'Murphy', 
                'contact_first_name' => 'Julie', 
                'phone' => '6505555787', 
                'address_line_1' => '5557 North Pendale Street',
                'address_line_2' => NULL,
                'city' => 'San Francisco', 
                'state' => 'CA', 
                'postal_code' => '94217', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1165, 
                'credit_limit' => '64600.00'
            ],
            [   
                'id' => 131,
                'customer_name' => 'Land of Toys Inc.',
                'contact_last_name' => 'Lee',
                'contact_first_name' => 'Kwai',
                'phone' => '2125557818',
                'address_line_1' => '897 Long Airport Avenue',
                'address_line_2' => NULL,
                'city' => 'NYC',
                'state' => 'NY',
                'postal_code' => '10022',
                'country' => 'USA',
                'sales_rep_employee_id' => 1323,
                'credit_limit' => '114900.00'
            ],
            [   
                'id' => 141, 
                'customer_name' => 'Euro+ Shopping Channel', 
                'contact_last_name' => 'Freyre', 
                'contact_first_name' => 'Diego ', 
                'phone' => '(91) 555 94 44',
                'address_line_1' => 'C/ Moralzarzal, 86',
                'address_line_2' => NULL,
                'city' => 'Madrid', 
                'state' => NULL, 
                'postal_code' => '28034', 
                'country' => 'Spain', 
                'sales_rep_employee_id' =>  1370, 
                'credit_limit' => '227600.00'
            ],
            [   
                'id' => 144, 
                'customer_name' => 'Volvo Model Replicas, Co', 
                'contact_last_name' => 'Berglund', 
                'contact_first_name' => 'Christina ', 
                'phone' => '0921-12 3555', 
                'address_line_1' => 'Berguvsvägen  8',
                'address_line_2' => NULL,
                'city' => 'Luleå', 
                'state' => NULL, 
                'postal_code' => 'S-958 22', 
                'country' => 'Sweden', 
                'sales_rep_employee_id' =>  1504, 
                'credit_limit' => '53100.00'
            ],
            [   
                'id' => 145, 
                'customer_name' => 'Danish Wholesale Imports', 
                'contact_last_name' => 'Petersen', 
                'contact_first_name' => 'Jytte ', 
                'phone' => '31 12 3555', 
                'address_line_1' => 'Vinbæltet 34',
                'address_line_2' => NULL,
                'city' => 'Kobenhavn', 
                'state' => NULL, 
                'postal_code' => '1734', 
                'country' => 'Denmark', 
                'sales_rep_employee_id' =>  1401, 
                'credit_limit' => '83400.00'
            ],
            [   
                'id' => 146, 
                'customer_name' => 'Saveley & Henriot, Co.', 
                'contact_last_name' => 'Saveley', 
                'contact_first_name' => 'Mary ', 
                'phone' => '78.32.5555', 
                'address_line_1' => '2, rue du Commerce',
                'address_line_2' => NULL,
                'city' => 'Lyon', 
                'state' => NULL, 
                'postal_code' => '69004', 
                'country' => 'France', 
                'sales_rep_employee_id' =>  1337, 
                'credit_limit' => '123900.00'
            ],
            [   
                'id' => 148, 
                'customer_name' => 'Dragon Souveniers, Ltd.', 
                'contact_last_name' => 'Natividad', 
                'contact_first_name' => 'Eric', 
                'phone' => '+65 221 7555',
                'address_line_1' => 'Bronz Sok.',
                'address_line_2' => 'Bronz Apt. 3/6 Tesvikiye',
                'city' => 'Singapore', 
                'state' => NULL, 
                'postal_code' => '079903', 
                'country' => 'Singapore', 
                'sales_rep_employee_id' =>  1621, 
                'credit_limit' => '103800.00'
            ],
            [   
                'id' => 151, 
                'customer_name' => 'Muscle Machine Inc', 
                'contact_last_name' => 'Young', 
                'contact_first_name' => 'Jeff', 
                'phone' => '2125557413',
                'address_line_1' => '4092 Furth Circle',
                'address_line_2' => 'Suite 400',
                'city' => 'NYC', 
                'state' => 'NY', 
                'postal_code' => '10022', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1286, 
                'credit_limit' => '138500.00'
            ],
            [   
                'id' => 157, 
                'customer_name' => 'Diecast Classics Inc.', 
                'contact_last_name' => 'Leong', 
                'contact_first_name' => 'Kelvin', 
                'phone' => '2155551555',
                'address_line_1' => '7586 Pompton St.',
                'address_line_2' => NULL,
                'city' => 'Allentown', 
                'state' => 'PA', 
                'postal_code' => '70267', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1216, 
                'credit_limit' => '100600.00'
            ],
            [   
                'id' => 161, 
                'customer_name' => 'Technics Stores Inc.', 
                'contact_last_name' => 'Hashimoto', 
                'contact_first_name' => 'Juri', 
                'phone' => '6505556809',
                'address_line_1' => '9408 Furth Circle',
                'address_line_2' => NULL,
                'city' => 'Burlingame', 
                'state' => 'CA', 
                'postal_code' => '94217', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1165, 
                'credit_limit' => '84600.00'
            ],
            [   
                'id' => 166, 
                'customer_name' => 'Handji Gifts& Co', 
                'contact_last_name' => 'Victorino',
                'contact_first_name' => 'Wendy',
                'phone' => '+65 224 1555',
                'address_line_1' => '106 Linden Road Sandown',
                'address_line_2' => '2nd Floor',
                'city' => 'Singapore', 
                'state' => NULL, 
                'postal_code' => '069045', 
                'country' => 'Singapore', 
                'sales_rep_employee_id' =>  1612, 
                'credit_limit' => '97900.00'
            ],
            [   
                'id' => 167, 
                'customer_name' => 'Herkku Gifts', 
                'contact_last_name' => 'Oeztan', 
                'contact_first_name' => 'Veysel',
                'phone' => '+47 2267 3215',
                'address_line_1' => 'Brehmen St. 121',
                'address_line_2' => 'PR 334 Sentrum',
                'city' => 'Bergen', 
                'state' => NULL, 
                'postal_code' => 'N 5804', 
                'country' => 'Norway  ', 
                'sales_rep_employee_id' =>  1504, 
                'credit_limit' => '96800.00'
            ],
            [   
                'id' => 168, 
                'customer_name' => 'American Souvenirs Inc', 
                'contact_last_name' => 'Franco', 
                'contact_first_name' => 'Keith', 
                'phone' => '2035557845',
                'address_line_1' => '149 Spinnaker Dr.',
                'address_line_2' => 'Suite 101',
                'city' => 'New Haven', 
                'state' => 'CT', 
                'postal_code' => '97823', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1286, 
                'credit_limit' => '0.00'
            ],
            [   
                'id' => 169, 
                'customer_name' => 'Porto Imports Co.', 
                'contact_last_name' => 'de Castro', 
                'contact_first_name' => 'Isabel ',
                'phone' => '(1) 356-5555',
                'address_line_1' => 'Estrada da saúde n. 58',
                'address_line_2' => NULL,
                'city' => 'Lisboa', 
                'state' => NULL, 
                'postal_code' => '1756', 
                'country' => 'Portugal', 
                'sales_rep_employee_id' =>  NULL, 
                'credit_limit' => '0.00'
            ],
            [   
                'id' => 171, 
                'customer_name' => 'Daedalus Designs Imports', 
                'contact_last_name' => 'Rancé',
                'contact_first_name' => 'Martine',
                'phone' => '20.16.1555',
                'address_line_1' => '184, chaussée de Tournai',
                'address_line_2' => NULL,
                'city' => 'Lille',
                'state' => NULL,
                'postal_code' => '59000',
                'country' => 'France',
                'sales_rep_employee_id' =>  1370,
                'credit_limit' => '82900.00'
            ],
            [   
                'id' => 172, 
                'customer_name' => 'La Corne D\'abondance, Co.', 
                'contact_last_name' => 'Bertrand', 
                'contact_first_name' => 'Marie',
                'phone' => '(1) 42.34.2555',
                'address_line_1' => '265, boulevard Charonne',
                'address_line_2' => NULL,
                'city' => 'Paris', 
                'state' => NULL, 
                'postal_code' => '75012', 
                'country' => 'France', 
                'sales_rep_employee_id' =>  1337, 
                'credit_limit' => '84300.00'
            ],
            [   
                'id' => 173, 
                'customer_name' => 'Cambridge Collectables Co.', 
                'contact_last_name' => 'Tseng', 
                'contact_first_name' => 'Jerry', 
                'phone' => '6175555555',
                'address_line_1' => '4658 Baden Av.',
                'address_line_2' => NULL,
                'city' => 'Cambridge', 
                'state' => 'MA', 
                'postal_code' => '51247', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1188, 
                'credit_limit' => '43400.00'
            ],
            [   
                'id' => 175, 
                'customer_name' => 'Gift Depot Inc.', 
                'contact_last_name' => 'King', 
                'contact_first_name' => 'Julie', 
                'phone' => '2035552570',
                'address_line_1' => '25593 South Bay Ln.',
                'address_line_2' => NULL,
                'city' => 'Bridgewater', 
                'state' => 'CT', 
                'postal_code' => '97562', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1323, 
                'credit_limit' => '84300.00'
            ],
            [   
                'id' => 177, 
                'customer_name' => 'Osaka Souveniers Co.', 
                'contact_last_name' => 'Kentary', 
                'contact_first_name' => 'Mory',
                'phone' => '+81 06 6342 5555',
                'address_line_1' => '1-6-20 Dojima',
                'address_line_2' => NULL,
                'city' => 'Kita-ku', 
                'state' => 'Osaka', 
                'postal_code' => ' 530-0003', 
                'country' => 'Japan', 
                'sales_rep_employee_id' =>  1621, 
                'credit_limit' => '81200.00'
            ],
            [   
                'id' => 181, 
                'customer_name' => 'Vitachrome Inc.', 
                'contact_last_name' => 'Frick', 
                'contact_first_name' => 'Michael', 
                'phone' => '2125551500',
                'address_line_1' => '2678 Kingston Rd.',
                'address_line_2' => 'Suite 101',
                'city' => 'NYC', 
                'state' => 'NY', 
                'postal_code' => '10022', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1286, 
                'credit_limit' => '76400.00'
            ],
            [   
                'id' => 186, 
                'customer_name' => 'Toys of Finland, Co.', 
                'contact_last_name' => 'Karttunen', 
                'contact_first_name' => 'Matti', 
                'phone' => '90-224 8555',
                'address_line_1' => 'Keskuskatu 45',
                'address_line_2' => NULL,
                'city' => 'Helsinki', 
                'state' => NULL, 
                'postal_code' => '21240', 
                'country' => 'Finland', 
                'sales_rep_employee_id' =>  1501, 
                'credit_limit' => '96500.00'
            ],
            [   
                'id' => 187, 
                'customer_name' => 'AV Stores, Co.', 
                'contact_last_name' => 'Ashworth', 
                'contact_first_name' => 'Rachel',
                'phone' => '(171) 555-1555',
                'address_line_1' => 'Fauntleroy Circus',
                'address_line_2' => NULL,
                'city' => 'Manchester', 
                'state' => NULL, 
                'postal_code' => 'EC2 5NT', 
                'country' => 'UK', 
                'sales_rep_employee_id' =>  1501, 
                'credit_limit' => '136800.00'
            ],
            [   
                'id' => 189, 
                'customer_name' => 'Clover Collections, Co.', 
                'contact_last_name' => 'Cassidy', 
                'contact_first_name' => 'Dean',
                'phone' => '+353 1862 1555',
                'address_line_1' => '25 Maiden Lane',
                'address_line_2' => 'Floor No. 4',
                'city' => 'Dublin', 
                'state' => NULL, 
                'postal_code' => '2', 
                'country' => 'Ireland', 
                'sales_rep_employee_id' =>  1504, 
                'credit_limit' => '69400.00'
            ],
            [   
                'id' => 198, 
                'customer_name' => 'Auto-Moto Classics Inc.', 
                'contact_last_name' => 'Taylor', 
                'contact_first_name' => 'Leslie', 
                'phone' => '6175558428',
                'address_line_1' => '16780 Pompton St.',
                'address_line_2' => NULL,
                'city' => 'Brickhaven', 
                'state' => 'MA', 
                'postal_code' => '58339', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1216, 
                'credit_limit' => '23000.00'
            ],
            [   
                'id' => 201, 
                'customer_name' => 'UK Collectables, Ltd.', 
                'contact_last_name' => 'Devon', 
                'contact_first_name' => 'Elizabeth',
                'phone' => '(171) 555-2282',
                'address_line_1' => '12, Berkeley Gardens Blvd',
                'address_line_2' => NULL,
                'city' => 'Liverpool', 
                'state' => NULL, 
                'postal_code' => 'WX1 6LT', 
                'country' => 'UK', 
                'sales_rep_employee_id' =>  1501, 
                'credit_limit' => '92700.00'
            ],
            [   
                'id' => 202, 
                'customer_name' => 'Canadian Gift Exchange Network', 
                'contact_last_name' => 'Tamuri', 
                'contact_first_name' => 'Yoshi ',
                'phone' => '(604) 555-3392',
                'address_line_1' => '1900 Oak St.',
                'address_line_2' => NULL,
                'city' => 'Vancouver', 
                'state' => 'BC', 
                'postal_code' => 'V3F 2K1', 
                'country' => 'Canada', 
                'sales_rep_employee_id' =>  1323, 
                'credit_limit' => '90300.00'
            ],
            [   
                'id' => 204, 
                'customer_name' => 'Online Mini Collectables', 
                'contact_last_name' => 'Barajas', 
                'contact_first_name' => 'Miguel', 
                'phone' => '6175557555',
                'address_line_1' => '7635 Spinnaker Dr.',
                'address_line_2' => NULL,
                'city' => 'Brickhaven', 
                'state' => 'MA', 
                'postal_code' => '58339', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1188, 
                'credit_limit' => '68700.00'
            ],
            [   
                'id' => 205, 
                'customer_name' => 'Toys4GrownUps.com', 
                'contact_last_name' => 'Young', 
                'contact_first_name' => 'Julie', 
                'phone' => '6265557265',
                'address_line_1' => '78934 Hillside Dr.',
                'address_line_2' => NULL,
                'city' => 'Pasadena', 
                'state' => 'CA', 
                'postal_code' => '90003', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1166, 
                'credit_limit' => '90700.00'
            ],
            [   
                'id' => 206, 
                'customer_name' => 'Asian Shopping Network, Co', 
                'contact_last_name' => 'Walker', 
                'contact_first_name' => 'Brydey',
                'phone' => '+612 9411 1555',
                'address_line_1' => 'Suntec Tower Three',
                'address_line_2' => '8 Temasek',
                'city' => 'Singapore', 
                'state' => NULL, 
                'postal_code' => '038988', 
                'country' => 'Singapore', 
                'sales_rep_employee_id' =>  NULL, 
                'credit_limit' => '0.00'
            ],
            [   
                'id' => 209, 
                'customer_name' => 'Mini Caravy', 
                'contact_last_name' => 'Citeaux', 
                'contact_first_name' => 'Frédérique ', 
                'phone' => '88.60.1555',
                'address_line_1' => '24, place Kléber',
                'address_line_2' => NULL,
                'city' => 'Strasbourg', 
                'state' => NULL, 
                'postal_code' => '67000', 
                'country' => 'France', 
                'sales_rep_employee_id' =>  1370, 
                'credit_limit' => '53800.00'
            ],
            [   
                'id' => 211, 
                'customer_name' => 'King Kong Collectables, Co.', 
                'contact_last_name' => 'Gao', 
                'contact_first_name' => 'Mike',
                'phone' => '+852 2251 1555',
                'address_line_1' => 'Bank of China Tower',
                'address_line_2' => '1 Garden Road',
                'city' => 'Central Hong Kong',
                'state' => NULL, 
                'postal_code' => NULL, 
                'country' => 'Hong Kong', 
                'sales_rep_employee_id' =>  1621, 
                'credit_limit' => '58600.00'
            ],
            [   
                'id' => 216, 
                'customer_name' => 'Enaco Distributors', 
                'contact_last_name' => 'Saavedra', 
                'contact_first_name' => 'Eduardo ',
                'phone' => '(93) 203 4555',
                'address_line_1' => 'Rambla de Cataluña, 23',
                'address_line_2' => NULL,
                'city' => 'Barcelona', 
                'state' => NULL, 
                'postal_code' => '08022', 
                'country' => 'Spain', 
                'sales_rep_employee_id' =>  1702, 
                'credit_limit' => '60300.00'
            ],
            [   
                'id' => 219, 
                'customer_name' => 'Boards & Toys Co.', 
                'contact_last_name' => 'Young', 
                'contact_first_name' => 'Mary', 
                'phone' => '3105552373',
                'address_line_1' => '4097 Douglas Av.',
                'address_line_2' => NULL,
                'city' => 'Glendale', 
                'state' => 'CA', 
                'postal_code' => '92561', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1166, 
                'credit_limit' => '11000.00'
            ],
            [   
                'id' => 223, 
                'customer_name' => 'Natürlich Autos', 
                'contact_last_name' => 'Kloss', 
                'contact_first_name' => 'Horst ', 
                'phone' => '0372-555188',
                'address_line_1' => 'Taucherstraße 10',
                'address_line_2' => NULL,
                'city' => 'Cunewalde', 
                'state' => NULL, 
                'postal_code' => '01307', 
                'country' => 'Germany', 
                'sales_rep_employee_id' =>  NULL, 
                'credit_limit' => '0.00'
            ],
            [   
                'id' => 227, 
                'customer_name' => 'Heintze Collectables', 
                'contact_last_name' => 'Ibsen', 
                'contact_first_name' => 'Palle', 
                'phone' => '86 21 3555',
                'address_line_1' => 'Smagsloget 45',
                'address_line_2' => NULL,
                'city' => 'Århus', 
                'state' => NULL, 
                'postal_code' => '8200', 
                'country' => 'Denmark', 
                'sales_rep_employee_id' =>  1401, 
                'credit_limit' => '120800.00'
            ],
            [   
                'id' => 233, 
                'customer_name' => 'Québec Home Shopping Network', 
                'contact_last_name' => 'Fresnière', 
                'contact_first_name' => 'Jean ',
                'phone' => '(514) 555-8054',
                'address_line_1' => '43 rue St. Laurent',
                'address_line_2' => NULL,
                'city' => 'Montréal', 
                'state' => 'Québec', 
                'postal_code' => 'H1J 1C3', 
                'country' => 'Canada', 
                'sales_rep_employee_id' =>  1286, 
                'credit_limit' => '48700.00'
            ],
            [   
                'id' => 237, 
                'customer_name' => 'ANG Resellers', 
                'contact_last_name' => 'Camino', 
                'contact_first_name' => 'Alejandra ',
                'phone' => '(91) 745 6555',
                'address_line_1' => 'Gran Vía, 1',
                'address_line_2' => NULL,
                'city' => 'Madrid', 
                'state' => NULL, 
                'postal_code' => '28001', 
                'country' => 'Spain', 
                'sales_rep_employee_id' =>  NULL, 
                'credit_limit' => '0.00'
            ],
            [   
                'id' => 239, 
                'customer_name' => 'Collectable Mini Designs Co.', 
                'contact_last_name' => 'Thompson', 
                'contact_first_name' => 'Valarie', 
                'phone' => '7605558146',
                'address_line_1' => '361 Furth Circle',
                'address_line_2' => NULL,
                'city' => 'San Diego', 
                'state' => 'CA', 
                'postal_code' => '91217', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1166, 
                'credit_limit' => '105000.00'
            ],
            [   
                'id' => 240, 
                'customer_name' => 'giftsbymail.co.uk', 
                'contact_last_name' => 'Bennett', 
                'contact_first_name' => 'Helen ',
                'phone' => '(198) 555-8888',
                'address_line_1' => 'Garden House',
                'address_line_2' => 'Crowther Way 23',
                'city' => 'Cowes', 
                'state' => 'Isle of Wight', 
                'postal_code' => 'PO31 7PJ', 
                'country' => 'UK', 
                'sales_rep_employee_id' =>  1501, 
                'credit_limit' => '93900.00'
            ],
            [   
                'id' => 242, 
                'customer_name' => 'Alpha Cognac', 
                'contact_last_name' => 'Roulet', 
                'contact_first_name' => 'Annette ', 
                'phone' => '61.77.6555',
                'address_line_1' => '1 rue Alsace-Lorraine',
                'address_line_2' => NULL,
                'city' => 'Toulouse', 
                'state' => NULL, 
                'postal_code' => '31000', 
                'country' => 'France', 
                'sales_rep_employee_id' =>  1370, 
                'credit_limit' => '61100.00'
            ],
            [   
                'id' => 247, 
                'customer_name' => 'Messner Shopping Network', 
                'contact_last_name' => 'Messner', 
                'contact_first_name' => 'Renate ', 
                'phone' => '069-0555984',
                'address_line_1' => 'Magazinweg 7',
                'address_line_2' => NULL,
                'city' => 'Frankfurt', 
                'state' => NULL, 
                'postal_code' => '60528', 
                'country' => 'Germany', 
                'sales_rep_employee_id' =>  NULL, 
                'credit_limit' => '0.00'
            ],
            [   
                'id' => 249, 
                'customer_name' => 'Amica Models & Co.', 
                'contact_last_name' => 'Accorti', 
                'contact_first_name' => 'Paolo ', 
                'phone' => '011-4988555',
                'address_line_1' => 'Via Monte Bianco 34',
                'address_line_2' => NULL,
                'city' => 'Torino', 
                'state' => NULL, 
                'postal_code' => '10100', 
                'country' => 'Italy', 
                'sales_rep_employee_id' =>  1401, 
                'credit_limit' => '113000.00'
            ],
            [   
                'id' => 250, 
                'customer_name' => 'Lyon Souveniers', 
                'contact_last_name' => 'Da Silva', 
                'contact_first_name' => 'Daniel',
                'phone' => '+33 1 46 62 7555',
                'address_line_1' => '27 rue du Colonel Pierre Avia',
                'address_line_2' => NULL,
                'city' => 'Paris', 
                'state' => NULL, 
                'postal_code' => '75508', 
                'country' => 'France', 
                'sales_rep_employee_id' =>  1337, 
                'credit_limit' => '68100.00'
            ],
            [   
                'id' => 256, 
                'customer_name' => 'Auto Associés & Cie.', 
                'contact_last_name' => 'Tonini', 
                'contact_first_name' => 'Daniel ', 
                'phone' => '30.59.8555',
                'address_line_1' => '67, avenue de l\'Europe',
                'address_line_2' => NULL,
                'city' => 'Versailles', 
                'state' => NULL, 
                'postal_code' => '78000', 
                'country' => 'France', 
                'sales_rep_employee_id' =>  1370, 
                'credit_limit' => '77900.00'
            ],
            [   
                'id' => 259, 
                'customer_name' => 'Toms Spezialitäten, Ltd', 
                'contact_last_name' => 'Pfalzheim', 
                'contact_first_name' => 'Henriette ', 
                'phone' => '0221-5554327',
                'address_line_1' => 'Mehrheimerstr. 369',
                'address_line_2' => NULL,
                'city' => 'Köln', 
                'state' => NULL, 
                'postal_code' => '50739', 
                'country' => 'Germany', 
                'sales_rep_employee_id' =>  1504, 
                'credit_limit' => '120400.00'
            ],
            [   
                'id' => 260, 
                'customer_name' => 'Royal Canadian Collectables, Ltd.', 
                'contact_last_name' => 'Lincoln', 
                'contact_first_name' => 'Elizabeth ',
                'phone' => '(604) 555-4555',
                'address_line_1' => '23 Tsawassen Blvd.',
                'address_line_2' => NULL,
                'city' => 'Tsawassen', 
                'state' => 'BC', 
                'postal_code' => 'T2F 8M4', 
                'country' => 'Canada', 
                'sales_rep_employee_id' =>  1323, 
                'credit_limit' => '89600.00'
            ],
            [   
                'id' => 273, 
                'customer_name' => 'Franken Gifts, Co', 
                'contact_last_name' => 'Franken', 
                'contact_first_name' => 'Peter ', 
                'phone' => '089-0877555',
                'address_line_1' => 'Berliner Platz 43',
                'address_line_2' => NULL,
                'city' => 'München', 
                'state' => NULL, 
                'postal_code' => '80805', 
                'country' => 'Germany', 
                'sales_rep_employee_id' =>  NULL, 
                'credit_limit' => '0.00'
            ],
            [   
                'id' => 276, 
                'customer_name' => 'Anna\'s Decorations, Ltd', 
                'contact_last_name' => 'O\'Hara', 
                'contact_first_name' => 'Anna', 
                'phone' => '02 9936 8555',
                'address_line_1' => '201 Miller Street',
                'address_line_2' => 'Level 15',
                'city' => 'North Sydney', 
                'state' => 'NSW', 
                'postal_code' => '2060', 
                'country' => 'Australia', 
                'sales_rep_employee_id' =>  1611, 
                'credit_limit' => '107800.00'
            ],
            [   
                'id' => 278, 
                'customer_name' => 'Rovelli Gifts', 
                'contact_last_name' => 'Rovelli', 
                'contact_first_name' => 'Giovanni ', 
                'phone' => '035-640555',
                'address_line_1' => 'Via Ludovico il Moro 22',
                'address_line_2' => NULL,
                'city' => 'Bergamo', 
                'state' => NULL, 
                'postal_code' => '24100', 
                'country' => 'Italy', 
                'sales_rep_employee_id' =>  1401, 
                'credit_limit' => '119600.00'
            ],
            [   
                'id' => 282, 
                'customer_name' => 'Souveniers And Things Co.', 
                'contact_last_name' => 'Huxley', 
                'contact_first_name' => 'Adrian',
                'phone' => '+61 2 9495 8555',
                'address_line_1' => 'Monitor Money Building',
                'address_line_2' => '815 Pacific Hwy',
                'city' => 'Chatswood', 
                'state' => 'NSW', 
                'postal_code' => '2067', 
                'country' => 'Australia', 
                'sales_rep_employee_id' =>  1611, 
                'credit_limit' => '93300.00'
            ],
            [   
                'id' => 286, 
                'customer_name' => 'Marta\'s Replicas Co.', 
                'contact_last_name' => 'Hernandez', 
                'contact_first_name' => 'Marta', 
                'phone' => '6175558555',
                'address_line_1' => '39323 Spinnaker Dr.',
                'address_line_2' => NULL,
                'city' => 'Cambridge', 
                'state' => 'MA', 
                'postal_code' => '51247', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1216, 
                'credit_limit' => '123700.00'
            ],
            [   
                'id' => 293, 
                'customer_name' => 'BG&E Collectables', 
                'contact_last_name' => 'Harrison', 
                'contact_first_name' => 'Ed',
                'phone' => '+41 26 425 50 01',
                'address_line_1' => 'Rte des Arsenaux 41 ',
                'address_line_2' => NULL,
                'city' => 'Fribourg', 
                'state' => NULL, 
                'postal_code' => '1700', 
                'country' => 'Switzerland', 
                'sales_rep_employee_id' =>  NULL, 
                'credit_limit' => '0.00'
            ],
            [   
                'id' => 298, 
                'customer_name' => 'Vida Sport, Ltd', 
                'contact_last_name' => 'Holz', 
                'contact_first_name' => 'Mihael', 
                'phone' => '0897-034555',
                'address_line_1' => 'Grenzacherweg 237',
                'address_line_2' => NULL,
                'city' => 'Genève', 
                'state' => NULL, 
                'postal_code' => '1203', 
                'country' => 'Switzerland', 
                'sales_rep_employee_id' =>  1702, 
                'credit_limit' => '141300.00'
            ],
            [   
                'id' => 299, 
                'customer_name' => 'Norway Gifts By Mail, Co.', 
                'contact_last_name' => 'Klaeboe', 
                'contact_first_name' => 'Jan',
                'phone' => '+47 2212 1555',
                'address_line_1' => 'Drammensveien 126A',
                'address_line_2' => 'PB 211 Sentrum',
                'city' => 'Oslo', 
                'state' => NULL, 
                'postal_code' => 'N 0106', 
                'country' => 'Norway', 
                'sales_rep_employee_id' =>  1504, 
                'credit_limit' => '95100.00'
            ],
            [   
                'id' => 303, 
                'customer_name' => 'Schuyler Imports', 
                'contact_last_name' => 'Schuyler', 
                'contact_first_name' => 'Bradley',
                'phone' => '+31 20 491 9555',
                'address_line_1' => 'Kingsfordweg 151',
                'address_line_2' => NULL,
                'city' => 'Amsterdam', 
                'state' => NULL, 
                'postal_code' => '1043 GR', 
                'country' => 'Netherlands', 
                'sales_rep_employee_id' =>  NULL, 
                'credit_limit' => '0.00'
            ],
            [   
                'id' => 307, 
                'customer_name' => 'Der Hund Imports', 
                'contact_last_name' => 'Andersen', 
                'contact_first_name' => 'Mel', 
                'phone' => '030-0074555',
                'address_line_1' => 'Obere Str. 57',
                'address_line_2' => NULL,
                'city' => 'Berlin', 
                'state' => NULL, 
                'postal_code' => '12209', 
                'country' => 'Germany', 
                'sales_rep_employee_id' =>  NULL, 
                'credit_limit' => '0.00'
            ],
            [   
                'id' => 311, 
                'customer_name' => 'Oulu Toy Supplies, Inc.', 
                'contact_last_name' => 'Koskitalo', 
                'contact_first_name' => 'Pirkko', 
                'phone' => '981-443655',
                'address_line_1' => 'Torikatu 38',
                'address_line_2' => NULL,
                'city' => 'Oulu', 
                'state' => NULL, 
                'postal_code' => '90110', 
                'country' => 'Finland', 
                'sales_rep_employee_id' =>  1501, 
                'credit_limit' => '90500.00'
            ],
            [   
                'id' => 314, 
                'customer_name' => 'Petit Auto', 
                'contact_last_name' => 'Dewey', 
                'contact_first_name' => 'Catherine ',
                'phone' => '(02) 5554 67',
                'address_line_1' => 'Rue Joseph-Bens 532',
                'address_line_2' => NULL,
                'city' => 'Bruxelles', 
                'state' => NULL, 
                'postal_code' => 'B-1180', 
                'country' => 'Belgium', 
                'sales_rep_employee_id' =>  1401, 
                'credit_limit' => '79900.00'
            ],
            [   
                'id' => 319, 
                'customer_name' => 'Mini Classics', 
                'contact_last_name' => 'Frick', 
                'contact_first_name' => 'Steve', 
                'phone' => '9145554562',
                'address_line_1' =>'3758 North Pendale Street',
                'address_line_2' => NULL,
                'city' => 'White Plains', 
                'state' => 'NY', 
                'postal_code' => '24067', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1323, 
                'credit_limit' => '102700.00'
            ],
            [   
                'id' => 320, 
                'customer_name' => 'Mini Creations Ltd.', 
                'contact_last_name' => 'Huang', 
                'contact_first_name' => 'Wing', 
                'phone' => '5085559555',
                'address_line_1' =>'4575 Hillside Dr.',
                'address_line_2' => NULL,
                'city' => 'New Bedford', 
                'state' => 'MA', 
                'postal_code' => '50553', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1188, 
                'credit_limit' => '94500.00'
            ],
            [   
                'id' => 321, 
                'customer_name' => 'Corporate Gift Ideas Co.', 
                'contact_last_name' => 'Brown', 
                'contact_first_name' => 'Julie', 
                'phone' => '6505551386',
                'address_line_1' => '7734 Strong St.',
                'address_line_2' => NULL,
                'city' => 'San Francisco', 
                'state' => 'CA', 
                'postal_code' => '94217', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1165, 
                'credit_limit' => '105000.00'
            ],
            [   
                'id' => 323, 
                'customer_name' => 'Down Under Souveniers, Inc', 
                'contact_last_name' => 'Graham', 
                'contact_first_name' => 'Mike',
                'phone' => '+64 9 312 5555',
                'address_line_1' => '162-164 Grafton Road',
                'address_line_2' => 'Level 2', 
                'city' => 'Auckland',
                'state' => NULL,
                'postal_code' => NULL, 
                'country' => 'New Zealand', 
                'sales_rep_employee_id' =>  1612, 
                'credit_limit' => '88000.00'
            ],
            [   
                'id' => 324, 
                'customer_name' => 'Stylish Desk Decors, Co.', 
                'contact_last_name' => 'Brown', 
                'contact_first_name' => 'Ann ',
                'phone' => '(171) 555-0297',
                'address_line_1' =>'35 King George',
                'address_line_2' => NULL,
                'city' => 'London', 
                'state' => NULL, 
                'postal_code' => 'WX3 6FW', 
                'country' => 'UK', 
                'sales_rep_employee_id' =>  1501, 
                'credit_limit' => '77000.00'
            ],
            [   
                'id' => 328, 
                'customer_name' => 'Tekni Collectables Inc.', 
                'contact_last_name' => 'Brown', 
                'contact_first_name' => 'William', 
                'phone' => '2015559350',
                'address_line_1' =>'7476 Moss Rd.',
                'address_line_2' => NULL,
                'city' => 'Newark', 
                'state' => 'NJ', 
                'postal_code' => '94019', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1323, 
                'credit_limit' => '43000.00'
            ],
            [   
                'id' => 333, 
                'customer_name' => 'Australian Gift Network, Co', 
                'contact_last_name' => 'Calaghan', 
                'contact_first_name' => 'Ben', 
                'phone' => '61-7-3844-6555',
                'address_line_1' => '31 Duncan St. West End',
                'address_line_2' => NULL,
                'city' => 'South Brisbane', 
                'state' => 'Queensland', 
                'postal_code' => '4101', 
                'country' => 'Australia', 
                'sales_rep_employee_id' =>  1611, 
                'credit_limit' => '51600.00'
            ],
            [   
                'id' => 334, 
                'customer_name' => 'Suominen Souveniers', 
                'contact_last_name' => 'Suominen', 
                'contact_first_name' => 'Kalle',
                'phone' => '+358 9 8045 555',
                'address_line_1' => 'Software Engineering Center',
                'address_line_2' => 'SEC Oy',
                'city' => 'Espoo', 
                'state' => NULL, 
                'postal_code' => 'FIN-02271',
                'country' => 'Finland', 
                'sales_rep_employee_id' =>  1501, 
                'credit_limit' => '98800.00'
            ],
            [   
                'id' => 335, 
                'customer_name' => 'Cramer Spezialitäten, Ltd', 
                'contact_last_name' => 'Cramer', 
                'contact_first_name' => 'Philip ', 
                'phone' => '0555-09555',
                'address_line_1' =>'Maubelstr. 90',
                'address_line_2' => NULL,
                'city' => 'Brandenburg', 
                'state' => NULL, 
                'postal_code' => '14776', 
                'country' => 'Germany', 
                'sales_rep_employee_id' =>  NULL, 
                'credit_limit' => '0.00'
            ],
            [   
                'id' => 339, 
                'customer_name' => 'Classic Gift Ideas, Inc', 
                'contact_last_name' => 'Cervantes', 
                'contact_first_name' => 'Francisca', 
                'phone' => '2155554695',
                'address_line_1' => '782 First Street',
                'address_line_2' => NULL,
                'city' => 'Philadelphia', 
                'state' => 'PA', 
                'postal_code' => '71270', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1188, 
                'credit_limit' => '81100.00'
            ],
            [   
                'id' => 344, 
                'customer_name' => 'CAF Imports',
                'contact_last_name' => 'Jesus', 
                'contact_first_name' => 'Fernandez',
                'phone' => '4 913 728 555',
                'address_line_1' => 'Merchants House',
                'address_line_2' => '27-30 Merchant\'s Quay',
                'city' => 'Madrid', 
                'state' => NULL, 
                'postal_code' => '28023', 
                'country' => 'Spain', 
                'sales_rep_employee_id' =>  1702, 
                'credit_limit' => '59600.00'
            ],
            [   
                'id' => 347, 
                'customer_name' => 'Men \'R\' US Retailers, Ltd.', 
                'contact_last_name' => 'Chandler', 
                'contact_first_name' => 'Brian', 
                'phone' => '2155554369',
                'address_line_1' =>'6047 Douglas Av.',
                'address_line_2' => NULL,
                'city' => 'Los Angeles', 
                'state' => 'CA', 
                'postal_code' => '91003', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1166, 
                'credit_limit' => '57700.00'
            ],
            [   
                'id' => 348, 
                'customer_name' => 'Asian Treasures, Inc.', 
                'contact_last_name' => 'McKenna', 
                'contact_first_name' => 'Patricia ', 
                'phone' => '2967 555',
                'address_line_1' =>'8 Johnstown Road',
                'address_line_2' => NULL,
                'city' => 'Cork', 
                'state' => 'Co. Cork', 
                'postal_code' => NULL, 
                'country' => 'Ireland', 
                'sales_rep_employee_id' =>  NULL, 
                'credit_limit' => '0.00'
            ],
            [   
                'id' => 350, 
                'customer_name' => 'Marseille Mini Autos', 
                'contact_last_name' => 'Lebihan', 
                'contact_first_name' => 'Laurence ', 
                'phone' => '91.24.4555',
                'address_line_1' =>'12, rue des Bouchers',
                'address_line_2' => NULL,
                'city' => 'Marseille', 
                'state' => NULL, 
                'postal_code' => '13008', 
                'country' => 'France', 
                'sales_rep_employee_id' =>  1337, 
                'credit_limit' => '65000.00'
            ],
            [   
                'id' => 353, 
                'customer_name' => 'Reims Collectables', 
                'contact_last_name' => 'Henriot', 
                'contact_first_name' => 'Paul ', 
                'phone' => '26.47.1555',
                'address_line_1' =>'59 rue de l\'Abbaye',
                'address_line_2' => NULL,
                'city' => 'Reims', 
                'state' => NULL, 
                'postal_code' => '51100', 
                'country' => 'France', 
                'sales_rep_employee_id' =>  1337, 
                'credit_limit' => '81100.00'
            ],
            [   
                'id' => 356, 
                'customer_name' => 'SAR Distributors, Co', 
                'contact_last_name' => 'Kuger', 
                'contact_first_name' => 'Armand',
                'phone' => '+27 21 550 3555',
                'address_line_1' =>'1250 Pretorius Street',
                'address_line_2' => NULL,
                'city' => 'Hatfield', 
                'state' => 'Pretoria', 
                'postal_code' => '0028', 
                'country' => 'South Africa', 
                'sales_rep_employee_id' =>  NULL, 
                'credit_limit' => '0.00'
            ],
            [   
                'id' => 357, 
                'customer_name' => 'GiftsForHim.com', 
                'contact_last_name' => 'MacKinlay', 
                'contact_first_name' => 'Wales', 
                'phone' => '64-9-3763555',
                'address_line_1' =>'199 Great North Road',
                'address_line_2' => NULL,
                'city' => 'Auckland', 
                'state' => NULL, 
                'postal_code' => NULL, 
                'country' => 'New Zealand', 
                'sales_rep_employee_id' =>  1612, 
                'credit_limit' => '77700.00'
            ],
            [   
                'id' => 361, 
                'customer_name' => 'Kommission Auto', 
                'contact_last_name' => 'Josephs', 
                'contact_first_name' => 'Karin', 
                'phone' => '0251-555259',
                'address_line_1' =>'Luisenstr. 48',
                'address_line_2' => NULL,
                'city' => 'Münster', 
                'state' => NULL, 
                'postal_code' => '44087', 
                'country' => 'Germany', 
                'sales_rep_employee_id' =>  NULL, 
                'credit_limit' => '0.00'
            ],
            [   
                'id' => 362, 
                'customer_name' => 'Gifts4AllAges.com', 
                'contact_last_name' => 'Yoshido', 
                'contact_first_name' => 'Juri', 
                'phone' => '6175559555',
                'address_line_1' =>'8616 Spinnaker Dr.',
                'address_line_2' => NULL,
                'city' => 'Boston', 
                'state' => 'MA', 
                'postal_code' => '51003', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1216, 
                'credit_limit' => '41900.00'
            ],
            [   
                'id' => 363, 
                'customer_name' => 'Online Diecast Creations Co.', 
                'contact_last_name' => 'Young', 
                'contact_first_name' => 'Dorothy', 
                'phone' => '6035558647',
                'address_line_1' =>'2304 Long Airport Avenue',
                'address_line_2' => NULL,
                'city' => 'Nashua', 
                'state' => 'NH', 
                'postal_code' => '62005', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1216, 
                'credit_limit' => '114200.00'
            ],
            [   
                'id' => 369, 
                'customer_name' => 'Lisboa Souveniers, Inc', 
                'contact_last_name' => 'Rodriguez', 
                'contact_first_name' => 'Lino ',
                'phone' => '(1) 354-2555',
                'address_line_1' =>'Jardim das rosas n. 32',
                'address_line_2' => NULL,
                'city' => 'Lisboa', 
                'state' => NULL, 
                'postal_code' => '1675', 
                'country' => 'Portugal', 
                'sales_rep_employee_id' =>  NULL, 
                'credit_limit' => '0.00'
            ],
            [   
                'id' => 376, 
                'customer_name' => 'Precious Collectables', 
                'contact_last_name' => 'Urs', 
                'contact_first_name' => 'Braun', 
                'phone' => '0452-076555',
                'address_line_1' =>'Hauptstr. 29',
                'address_line_2' => NULL,
                'city' => 'Bern', 
                'state' => NULL, 
                'postal_code' => '3012', 
                'country' => 'Switzerland', 
                'sales_rep_employee_id' =>  1702, 
                'credit_limit' => '0.00'
            ],
            [   
                'id' => 379, 
                'customer_name' => 'Collectables For Less Inc.', 
                'contact_last_name' => 'Nelson', 
                'contact_first_name' => 'Allen', 
                'phone' => '6175558555',
                'address_line_1' =>'7825 Douglas Av.',
                'address_line_2' => NULL,
                'city' => 'Brickhaven', 
                'state' => 'MA', 
                'postal_code' => '58339', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1188, 
                'credit_limit' => '70700.00'
            ],
            [   
                'id' => 381, 
                'customer_name' => 'Royale Belge', 
                'contact_last_name' => 'Cartrain', 
                'contact_first_name' => 'Pascale ',
                'phone' => '(071) 23 67 2555',
                'address_line_1' =>'Boulevard Tirou, 255',
                'address_line_2' => NULL,
                'city' => 'Charleroi', 
                'state' => NULL, 
                'postal_code' => 'B-6000', 
                'country' => 'Belgium', 
                'sales_rep_employee_id' =>  1401, 
                'credit_limit' => '23500.00'
            ],
            [   
                'id' => 382, 
                'customer_name' => 'Salzburg Collectables', 
                'contact_last_name' => 'Pipps', 
                'contact_first_name' => 'Georg ', 
                'phone' => '6562-9555',
                'address_line_1' =>'Geislweg 14',
                'address_line_2' => NULL,
                'city' => 'Salzburg', 
                'state' => NULL, 
                'postal_code' => '5020', 
                'country' => 'Austria', 
                'sales_rep_employee_id' =>  1401, 
                'credit_limit' => '71700.00'
            ],
            [   
                'id' => 385, 
                'customer_name' => 'Cruz & Sons Co.', 
                'contact_last_name' => 'Cruz', 
                'contact_first_name' => 'Arnold',
                'phone' => '+63 2 555 3587',
                'address_line_1' =>'15 McCallum Street',
                'address_line_2' => 'NatWest Center #13-03',
                'city' => 'Makati City', 
                'state' => NULL, 
                'postal_code' => '1227 MM', 
                'country' => 'Philippines', 
                'sales_rep_employee_id' =>  1621, 
                'credit_limit' => '81500.00'
            ],
            [   
                'id' => 386, 
                'customer_name' => 'L\'ordine Souveniers', 
                'contact_last_name' => 'Moroni', 
                'contact_first_name' => 'Maurizio ', 
                'phone' => '0522-556555',
                'address_line_1' =>'Strada Provinciale 124',
                'address_line_2' => NULL,
                'city' => 'Reggio Emilia', 
                'state' => NULL, 
                'postal_code' => '42100', 
                'country' => 'Italy', 
                'sales_rep_employee_id' =>  1401, 
                'credit_limit' => '121400.00'
            ],
            [   
                'id' => 398, 
                'customer_name' => 'Tokyo Collectables, Ltd', 
                'contact_last_name' => 'Shimamura', 
                'contact_first_name' => 'Akiko',
                'phone' => '+81 3 3584 0555',
                'address_line_1' =>'2-2-8 Roppongi',
                'address_line_2' => NULL,
                'city' => 'Minato-ku', 
                'state' => 'Tokyo', 
                'postal_code' => '106-0032', 
                'country' => 'Japan', 
                'sales_rep_employee_id' =>  1621, 
                'credit_limit' => '94400.00'
            ],
            [   
                'id' => 406, 
                'customer_name' => 'Auto Canal+ Petit', 
                'contact_last_name' => 'Perrier', 
                'contact_first_name' => 'Dominique',
                'phone' => '(1) 47.55.6555',
                'address_line_1' =>'25, rue Lauriston',
                'address_line_2' => NULL,
                'city' => 'Paris', 
                'state' => NULL, 
                'postal_code' => '75016', 
                'country' => 'France', 
                'sales_rep_employee_id' =>  1337, 
                'credit_limit' => '95000.00'
            ],
            [   
                'id' => 409, 
                'customer_name' => 'Stuttgart Collectable Exchange', 
                'contact_last_name' => 'Müller', 
                'contact_first_name' => 'Rita ', 
                'phone' => '0711-555361',
                'address_line_1' =>'Adenauerallee 900',
                'address_line_2' => NULL,
                'city' => 'Stuttgart', 
                'state' => NULL, 
                'postal_code' => '70563', 
                'country' => 'Germany', 
                'sales_rep_employee_id' =>  NULL, 
                'credit_limit' => '0.00'
            ],
            [   
                'id' => 412, 
                'customer_name' => 'Extreme Desk Decorations, Ltd', 
                'contact_last_name' => 'McRoy', 
                'contact_first_name' => 'Sarah', 
                'phone' => '04 499 9555',
                'address_line_1' =>'101 Lambton Quay',
                'address_line_2' => 'Level 11',
                'city' => 'Wellington', 
                'state' => NULL, 
                'postal_code' => NULL, 
                'country' => 'New Zealand', 
                'sales_rep_employee_id' =>  1612, 
                'credit_limit' => '86800.00'
            ],
            [   
                'id' => 415, 
                'customer_name' => 'Bavarian Collectables Imports, Co.', 
                'contact_last_name' => 'Donnermeyer', 
                'contact_first_name' => 'Michael', 
                'phone' => ' +49 89 61 08 9555',
                'address_line_1' =>'Hansastr. 15',
                'address_line_2' => NULL,
                'city' => 'Munich', 
                'state' => NULL, 
                'postal_code' => '80686', 
                'country' => 'Germany', 
                'sales_rep_employee_id' =>  1504, 
                'credit_limit' => '77000.00'
            ],
            [   
                'id' => 424, 
                'customer_name' => 'Classic Legends Inc.', 
                'contact_last_name' => 'Hernandez', 
                'contact_first_name' => 'Maria', 
                'phone' => '2125558493',
                'address_line_1' =>'5905 Pompton St.',
                'address_line_2' => 'Suite 750',
                'city' => 'NYC', 
                'state' => 'NY', 
                'postal_code' => '10022', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1286, 
                'credit_limit' => '67500.00'
            ],
            [   
                'id' => 443, 
                'customer_name' => 'Feuer Online Stores, Inc', 
                'contact_last_name' => 'Feuer', 
                'contact_first_name' => 'Alexander ', 
                'phone' => '0342-555176',
                'address_line_1' =>'Heerstr. 22',
                'address_line_2' => NULL,
                'city' => 'Leipzig', 
                'state' => NULL, 
                'postal_code' => '04179', 
                'country' => 'Germany', 
                'sales_rep_employee_id' =>  NULL, 
                'credit_limit' => '0.00'
            ],
            [   
                'id' => 447, 
                'customer_name' => 'Gift Ideas Corp.', 
                'contact_last_name' => 'Lewis', 
                'contact_first_name' => 'Dan', 
                'phone' => '2035554407',
                'address_line_1' => '2440 Pompton St.',
                'address_line_2' => NULL,
                'city' => 'Glendale', 
                'state' => 'CT', 
                'postal_code' => '97561', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1323, 
                'credit_limit' => '49700.00'
            ],
            [   
                'id' => 448, 
                'customer_name' => 'Scandinavian Gift Ideas', 
                'contact_last_name' => 'Larsson', 
                'contact_first_name' => 'Martha', 
                'phone' => '0695-34 6555',
                'address_line_1' => 'Åkergatan 24',
                'address_line_2' => NULL,
                'city' => 'Bräcke',
                'state' => NULL, 
                'postal_code' => 'S-844 67', 
                'country' => 'Sweden', 
                'sales_rep_employee_id' =>  1504, 
                'credit_limit' => '116400.00'
            ],
            [   
                'id' => 450, 
                'customer_name' => 'The Sharp Gifts Warehouse', 
                'contact_last_name' => 'Frick', 
                'contact_first_name' => 'Sue', 
                'phone' => '4085553659',
                'address_line_1' =>'3086 Ingle Ln.',
                'address_line_2' => NULL,
                'city' => 'San Jose', 
                'state' => 'CA', 
                'postal_code' => '94217', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1165, 
                'credit_limit' => '77600.00'
            ],
            [   
                'id' => 452, 
                'customer_name' => 'Mini Auto Werke', 
                'contact_last_name' => 'Mendel', 
                'contact_first_name' => 'Roland ', 
                'phone' => '7675-3555',
                'address_line_1' =>'Kirchgasse 6',
                'address_line_2' => NULL,
                'city' => 'Graz', 
                'state' => NULL, 
                'postal_code' => '8010', 
                'country' => 'Austria', 
                'sales_rep_employee_id' =>  1401, 
                'credit_limit' => '45300.00'
            ],
            [   
                'id' => 455, 
                'customer_name' => 'Super Scale Inc.', 
                'contact_last_name' => 'Murphy', 
                'contact_first_name' => 'Leslie', 
                'phone' => '2035559545',
                'address_line_1' =>'567 North Pendale Street',
                'address_line_2' => NULL,
                'city' => 'New Haven', 
                'state' => 'CT', 
                'postal_code' => '97823', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1286, 
                'credit_limit' => '95400.00'
            ],
            [   
                'id' => 456, 
                'customer_name' => 'Microscale Inc.', 
                'contact_last_name' => 'Choi', 
                'contact_first_name' => 'Yu', 
                'phone' => '2125551957',
                'address_line_1' =>'5290 North Pendale Street',
                'address_line_2' => 'Suite 200',
                'city' => 'NYC', 
                'state' => 'NY', 
                'postal_code' => '10022', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1286, 
                'credit_limit' => '39800.00'
            ],
            [   
                'id' => 458, 
                'customer_name' => 'Corrida Auto Replicas, Ltd', 
                'contact_last_name' => 'Sommer', 
                'contact_first_name' => 'Martín ',
                'phone' => '(91) 555 22 82',
                'address_line_1' =>'C/ Araquil, 67',
                'address_line_2' => NULL,
                'city' => 'Madrid', 
                'state' => NULL, 
                'postal_code' => '28023', 
                'country' => 'Spain', 
                'sales_rep_employee_id' =>  1702, 
                'credit_limit' => '104600.00'
            ],
            [   
                'id' => 459, 
                'customer_name' => 'Warburg Exchange', 
                'contact_last_name' => 'Ottlieb', 
                'contact_first_name' => 'Sven ', 
                'phone' => '0241-039123',
                'address_line_1' =>'Walserweg 21',
                'address_line_2' => NULL,
                'city' => 'Aachen', 
                'state' => NULL, 
                'postal_code' => '52066', 
                'country' => 'Germany', 
                'sales_rep_employee_id' =>  NULL, 
                'credit_limit' => '0.00'
            ],
            [   
                'id' => 462, 
                'customer_name' => 'FunGiftIdeas.com', 
                'contact_last_name' => 'Benitez', 
                'contact_first_name' => 'Violeta', 
                'phone' => '5085552555',
                'address_line_1' =>'1785 First Street',
                'address_line_2' => NULL,
                'city' => 'New Bedford', 
                'state' => 'MA', 
                'postal_code' => '50553', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1216, 
                'credit_limit' => '85800.00'
            ],
            [   
                'id' => 465, 
                'customer_name' => 'Anton Designs, Ltd.', 
                'contact_last_name' => 'Anton', 
                'contact_first_name' => 'Carmen',
                'phone' => '+34 913 728555',
                'address_line_1' =>'c/ Gobelas, 19-1 Urb. La Florida',
                'address_line_2' => NULL,
                'city' => 'Madrid', 
                'state' => NULL, 
                'postal_code' => '28023', 
                'country' => 'Spain', 
                'sales_rep_employee_id' =>  NULL, 
                'credit_limit' => '0.00'
            ],
            [   
                'id' => 471, 
                'customer_name' => 'Australian Collectables, Ltd', 
                'contact_last_name' => 'Clenahan', 
                'contact_first_name' => 'Sean', 
                'phone' => '61-9-3844-6555',
                'address_line_1' =>'7 Allen Street',
                'address_line_2' => NULL,
                'city' => 'Glen Waverly', 
                'state' => 'Victoria', 
                'postal_code' => '3150', 
                'country' => 'Australia', 
                'sales_rep_employee_id' =>  1611, 
                'credit_limit' => '60300.00'
            ],
            [   
                'id' => 473, 
                'customer_name' => 'Frau da Collezione', 
                'contact_last_name' => 'Ricotti', 
                'contact_first_name' => 'Franco',
                'phone' => '+39 022515555',
                'address_line_1' =>'20093 Cologno Monzese',
                'address_line_2' => 'Alessandro Volta 16',
                'city' => 'Milan', 
                'state' => NULL, 
                'postal_code' => NULL, 
                'country' => 'Italy', 
                'sales_rep_employee_id' =>  1401, 
                'credit_limit' => '34800.00'
            ],
            [   
                'id' => 475, 
                'customer_name' => 'West Coast Collectables Co.', 
                'contact_last_name' => 'Thompson', 
                'contact_first_name' => 'Steve', 
                'phone' => '3105553722',
                'address_line_1' =>'3675 Furth Circle',
                'address_line_2' => NULL,
                'city' => 'Burbank', 
                'state' => 'CA', 
                'postal_code' => '94019', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1166, 
                'credit_limit' => '55400.00'
            ],
            [   
                'id' => 477, 
                'customer_name' => 'Mit Vergnügen & Co.', 
                'contact_last_name' => 'Moos', 
                'contact_first_name' => 'Hanna ', 
                'phone' => '0621-08555',
                'address_line_1' =>'Forsterstr. 57',
                'address_line_2' => NULL,
                'city' => 'Mannheim', 
                'state' => NULL, 
                'postal_code' => '68306', 
                'country' => 'Germany', 
                'sales_rep_employee_id' =>  NULL, 
                'credit_limit' => '0.00'
            ],
            [   
                'id' => 480, 
                'customer_name' => 'Kremlin Collectables, Co.', 
                'contact_last_name' => 'Semenov', 
                'contact_first_name' => 'Alexander ',
                'phone' => '+7 812 293 0521',
                'address_line_1' =>'2 Pobedy Square',
                'address_line_2' => NULL,
                'city' => 'Saint Petersburg', 
                'state' => NULL, 
                'postal_code' => '196143', 
                'country' => 'Russia', 
                'sales_rep_employee_id' =>  NULL, 
                'credit_limit' => '0.00'
            ],
            [   
                'id' => 481, 
                'customer_name' => 'Raanan Stores, Inc', 
                'contact_last_name' => 'Altagar,G M',
                'contact_first_name' =>  'Raanan', 
                'phone' => '+ 972 9 959 8555',
                'address_line_1' =>'3 Hagalim Blv.',
                'address_line_2' => NULL,
                'city' => 'Herzlia', 
                'state' => NULL, 
                'postal_code' => '47625', 
                'country' => 'Israel', 
                'sales_rep_employee_id' =>  NULL, 
                'credit_limit' => '0.00'
            ],
            [   
                'id' => 484, 
                'customer_name' => 'Iberia Gift Imports, Corp.', 
                'contact_last_name' => 'Roel', 
                'contact_first_name' => 'José Pedro',
                'phone' => '(95) 555 82 82',
                'address_line_1' =>'C/ Romero, 33',
                'address_line_2' => NULL,
                'city' => 'Sevilla', 
                'state' => NULL, 
                'postal_code' => '41101', 
                'country' => 'Spain', 
                'sales_rep_employee_id' =>  1702, 
                'credit_limit' => '65700.00'
            ],
            [   
                'id' => 486, 
                'customer_name' => 'Motor Mint Distributors Inc.', 
                'contact_last_name' => 'Salazar', 
                'contact_first_name' => 'Rosa', 
                'phone' => '2155559857',
                'address_line_1' =>'11328 Douglas Av.',
                'address_line_2' => NULL,
                'city' => 'Philadelphia', 
                'state' => 'PA', 
                'postal_code' => '71270', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1323, 
                'credit_limit' => '72600.00'
            ],
            [   
                'id' => 487, 
                'customer_name' => 'Signal Collectibles Ltd.', 
                'contact_last_name' => 'Taylor', 
                'contact_first_name' => 'Sue', 
                'phone' => '4155554312',
                'address_line_1' =>'2793 Furth Circle',
                'address_line_2' => NULL,
                'city' => 'Brisbane', 
                'state' => 'CA', 
                'postal_code' => '94217', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1165, 
                'credit_limit' => '60300.00'
            ],
            [   
                'id' => 489, 
                'customer_name' => 'Double Decker Gift Stores, Ltd', 
                'contact_last_name' => 'Smith', 
                'contact_first_name' => 'Thomas ',
                'phone' => '(171) 555-7555',
                'address_line_1' =>'120 Hanover Sq.',
                'address_line_2' => NULL,
                'city' => 'London', 
                'state' => NULL, 
                'postal_code' => 'WA1 1DP', 
                'country' => 'UK', 
                'sales_rep_employee_id' =>  1501, 
                'credit_limit' => '43300.00'
            ],
            [   
                'id' => 495, 
                'customer_name' => 'Diecast Collectables', 
                'contact_last_name' => 'Franco', 
                'contact_first_name' => 'Valarie', 
                'phone' => '6175552555',
                'address_line_1' =>'6251 Ingle Ln.',
                'address_line_2' => NULL,
                'city' => 'Boston', 
                'state' => 'MA', 
                'postal_code' => '51003', 
                'country' => 'USA', 
                'sales_rep_employee_id' =>  1188, 
                'credit_limit' => '85100.00'
            ],
            [   
                'id' => 496, 
                'customer_name' => 'Kelly\'s Gift Shop', 
                'contact_last_name' => 'Snowden', 
                'contact_first_name' => 'Tony',
                'phone' => '+64 9 5555500',
                'address_line_1' =>'Arenales 1938 3\'A\'',
                'address_line_2' => NULL,
                'city' => 'Auckland  ', 
                'state' => NULL, 
                'postal_code' => NULL, 
                'country' => 'New Zealand', 
                'sales_rep_employee_id' =>  1612, 
                'credit_limit' => '110000.00'
            ],
        ];

        Customer::insert($customers);
    }
}
